CREATE TABLE Service2Addon (
 Service2AddonID int NOT NULL IDENTITY(1,1),
 ServiceID int NOT NULL,
 AddonID int NOT NULL,
 Quantity int NOT NULL,
 CONSTRAINT PK_Service2AddonID PRIMARY KEY (Service2AddonID),
 CONSTRAINT FK_ServiceID FOREIGN KEY (ServiceID) REFERENCES [Services](ServicesID) ON DELETE CASCADE ON UPDATE CASCADE,
 CONSTRAINT FK_AddonID FOREIGN KEY (AddonID) REFERENCES [Addons](AddonID) ON UPDATE CASCADE,
);